(define-module twitter
  (use rfc.uri)
  (use gauche.charconv)
  (use mi.http)
  (export-all)
  )
(select-module twitter)

(define-class <twitter> ()
  ((user :init-keyword :user)
   (password :init-keyword :password)
   (formats :init-keyword :formats :init-value "xml")
   (base-uri :init-value "http://twitter.com/")
   (update :init-value "statuses/update.")
   (friend-timeline :init-value "statuses/friends_timeline.")
   (user-timeline :init-value "statuses/user_timeline.")
   (status-max :init-value 160)
   (user/pass)
   )
  )
(define-method initialize ((self <twitter>) initargs)
  (next-method)
  (let ((user (ref self 'user)) (password (ref self 'password))
        (base (ref self 'base-uri)) (formats (ref self 'formats)))
    (set! (ref self 'user/pass) #`",|user|:,password")
    (for-each
      (lambda (tag)
        (set! (ref self tag) #`",base,(ref self tag),formats")
        ) '(update friend-timeline user-timeline))
    )
  )

(define (my-conv str)
  (ces-convert (uri-encode-string str) "*JP")
  )

(define (with-twitter fn . args)
  (let-keywords args ((user "") (password ""))
    (unless (or (string=? user "") (string=? password ""))
      (fn (make <twitter> :user user :password password))
      )
    )
  )

(define (twitter-update twitter-obj status)
  (if (< (string-length status) (ref twitter-obj 'status-max))
    (let1 uri #`",(ref twitter-obj 'update)?status=,(my-conv status)"
      (open-uri uri :method 'post :user/pass (ref twitter-obj 'user/pass))
      )
    )
  )

(define (twitter-friend-timeline twitter-obj)
  (open-uri (ref twitter-obj 'friend-timeline)
            :user/pass (ref twitter-obj 'user/pass))
  )

(define (twitter-user-timeline twitter-obj)
  (open-uri (ref twitter-obj 'user-timeline)
            :user/pass (ref twitter-obj 'user/pass))
  )

(provide "twitter")
